### ISSUE TITLE
"Architecture" tag in docker metadata is "amd64"

### ISSUE THREAD

**Issue by anguslees** [m3adow/armhf_docker_base_images#3]
Just fyi, the "Architecture" tag in your builds on docker hub say "amd64" and not "armv7l" - this confuses docker2aci ;)

**Comment by m3adow** [comment]
Hi, thanks for the info.
I didn't know there's any "semi-official" tagging for architecture. I wasn't able to find a lot of info about it as well. I've just pushed 72289be. I hope this is what you expected.
