### ISSUE TITLE
armhf-alpine:3.4 is actually still 3.3.3

### ISSUE THREAD

**Issue by SeijiSuenaga** [m3adow/armhf_docker_base_images#4]
Just a heads-up: The filesystem in the new 3.4 image is apparently identical to the one in the 3.3 image.

See "docker history" for each.  Also see the /etc/alpine-release file, which still says 3.3.3 in the 3.4 image.

**Comment by m3adow** [comment]
Thanks for that report. I updated the repo, but forgot to pull the changes to my Raspberry Pi. I've now updated it there and additionally configured an "auto pull" of changes, so I hope this won't happen again.
