### ISSUE TITLE
No weekly builds?

### ISSUE THREAD

**Issue by funkyfuture** [m3adow/armhf_docker_base_images#5]
ciao, thanks for providing these images.

i just noticed that the builds are thirteen days old though they are supposed to be built weekly. is everything alright?

**Comment by m3adow** [comment]
Hey,

thanks for the heads up. I recently reconfigured my Pi and forgot to configure the cron job for the builds. Fixed now.

**Comment by m3adow** [comment]
Just an FYI:

I recently moved and could not yet set up my Pi. Furthermore we have problems with the Internet. So the weekly builds will be halted for a couple of weeks.

**Comment by funkyfuture** [comment]
ai'ght, settle in relaxed!
