### ISSUE TITLE
Alpine 3.5 image is not available on docker hub

### ISSUE THREAD

**Issue by seblucas** [m3adow/armhf_docker_base_images#6]
I saw the commit for Alpine 3.5 but there was no build since. Is that normal ?

Thanks a lot for your work.

**Comment by m3adow** [comment]
Thanks for the report. It seems the cron daemon on my Raspberry Pi stopped for some reason. I hope everything is fixed now. While I was at it, I also removed Alpine 3.2 as I feel that three versions are more than enough.

**Comment by seblucas** [comment]
Pulling now thanks ;)
