### ISSUE TITLE
Alpine 3.6 errored on travis

### ISSUE THREAD

**Issue by seblucas** [m3adow/armhf_docker_base_images#7]
Hi,

I was happy when I saw you made a commit enabling Alpine 3.6 but it seems Travis errored ...

https://travis-ci.org/m3adow/armhf_docker_base_images/jobs/240366512

Maybe you didn't see that ;).

**Comment by m3adow** [comment]
Hiho,

The error you mentioned was an expected one as the files the script needed didn't exist yet (it was only a configuration commit). The commit afterwards fixed this problem (https://travis-ci.org/m3adow/armhf_docker_base_images/builds/240369637).

BUT I forgot to add a 3.6 tag to Docker hub, which I did only realize thanks to your report. Thanks for that!
